spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: ""
    url: "jdbc:mysql://127.0.0.1:3306/kotlin_sample?user=root&password=admin&characterEncoding=UTF8&connectionCollation=utf8mb4_bin&useSSL=false"
